apiVersion: apps/v1
kind: Deployment
metadata:
  name: byzantine-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: byzantine-operator
  template:
    metadata:
      labels:
        app: byzantine-operator
    spec:
      serviceAccountName: byzantine-operator
      containers:
      - name: operator
        image: byzantine-operator:v1
        imagePullPolicy: Never
        env:
        - name: PROMETHEUS_URL
          value: "http://prometheus-service.default.svc:9090"
        resources:
          limits:
            memory: "300Mi"
            cpu: "200m"
          requests:
            memory: "100Mi"
            cpu: "100m"
