apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-baseline
  labels:
    app: nginx-baseline
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-baseline
  template:
    metadata:
      labels:
        app: nginx-baseline
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-baseline-svc
spec:
  selector:
    app: nginx-baseline
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
